services:
  php-apache:
    build: .
    container_name: flood-monitor-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html # Twój kod
      - vendor_data:/var/www/html/vendor # TRIK: vendor z obrazu/volumenu, nie z hosta
      - ./uploads:/var/www/html/uploads # (opcjonalnie) żeby obrazki były na hoście
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flood-monitor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flood_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: flood-monitor-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
  vendor_data:
